### ISSUE TITLE
Installation on MacOS (Catalina)

### ISSUE THREAD

**Issue by serpent213** [asciitosvg/asciitosvg#22]
Not knowing *go* very well, I just tried the following:

    % brew install go
    [...]
    % go get github.com/asciitosvg/asciitosvg/cmd/a2s
    % go get -v github.com/asciitosvg/asciitosvg/cmd/a2s
    %

Nothing seems to happen.  🤷🏼‍♂️

Any advice?

**Comment by dhobsd** [comment]
I'm so sorry for the lack of quick reply here; I don't spend a lot of time on GitHub recently and my notifications tabs get overwhelmed by a few very active repositories I've contributed to over time.

By default, `go get` will fetch and install whatever it fetches into `$GOPATH`, which, if unset, defaults to `$HOME/go`. When you ran `go get` the first time, it likely took a little bit and dropped you to a prompt with no output. When you ran `go get -v`, it did the same, but faster.

What I suspect happened is that the first invocation installed `a2s` into `/Users/[you]/go/bin` silently. The second attempt looked up whether anything needed fetching, decided it did not (because you already had run `go get` successfully), and then did not tell you that's the decision it came to.

The upshot of this is that if you add `$HOME/go/bin` to your `$PATH`, this should "just work".
